network: 'mainnet'
metaChainShardId: 4294967295
sentryDsn: ${SENTRY_DSN}
github:
  token: ${GITHUB_TOKEN}
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 1000
  transactionCompleted: true
  transactionCompletedMaxLookBehind: 100
  transactionBatch: true
  transactionBatchMaxLookBehind: 100
  cacheWarmer: true
  fastWarm: true
  queueWorker: true
  elasticUpdater: false
  statusChecker: false
flags:
  useRequestCaching: true
  useKeepAliveAgent: true
  useTracing: false
  useRequestLogging: true
  useVmQueryTracing: true
  processNfts: true
  indexer-v3: true
  collectionPropertiesFromGateway: false
features:
  eventsNotifier:
    enabled: false
    port: 5674
    url: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}'
    exchange: 'all_events'
    queue: 'api-process-logs-and-events'
  guestCaching:
    enabled: false
    hitsThreshold: 100
    ttl: 12
  updateCollectionExtraDetails:
    enabled: false
  marketplace:
    enabled: false
    serviceUrl: 'https://nfts-graph.multiversx.com/graphql'
  exchange:
    enabled: false
    serviceUrl: 'https://graph.xexchange.com/graphql'
  dataApi:
    enabled: false
    serviceUrl: 'https://data-api.multiversx.com'
  auth:
    enabled: false
    maxExpirySeconds: 86400
    acceptedOrigins:
      - ''
    admins:
      - ''
    jwtSecret: ''
image:
  width: 600
  height: 600
  type: 'png'
aws:
  s3KeyId: ''
  s3Secret: ''
  s3Bucket: 'media.elrond.com'
  s3Region: ''
urls:
  self: 'https://api.multiversx.com'
  api:
    - 'https://mx-api.bicarus.io'
    - 'https://api.multiversx.com'
    - 'https://devnet-api.multiversx.com'
    - 'https://testnet-api.multiversx.com'
  elastic:
    - ${ELASTICSEARCH_URLS}
  gateway:
    - ${GATEWAY_URLS}
  verifier: 'https://play-api.multiversx.com'
  redis:
    host: '${REDIS_HOST}'
    port: '${REDIS_PORT}'
  rabbitmq: 'amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}'
  providers: 'https://delegation-api.multiversx.com/providers'
  delegation: 'https://delegation-api.multiversx.com'
  media: 'https://media.elrond.com'
  nftThumbnails: 'https://media.elrond.com/nfts/thumbnail'
  tmp: '/tmp'
  ipfs: 'https://ipfs.io/ipfs'
  socket: 'socket-fra.elrond.com'
  maiarId: 'https://id-api.multiversx.com'
indexer:
  type: 'elastic'
  maxPagination: 10000
database:
  enabled: ${DATABASE_ENABLE}
  url: 'mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME}'
  type: 'mysql'
  host: '${MYSQL_HOST}'
  port: ${MYSQL_PORT}
  username: '${MYSQL_USER}'
  password: '${MYSQL_PASS}'
  database: '${MYSQL_DBNAME}'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 50
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  metabonding: 'erd1qqqqqqqqqqqqqpgq50dge6rrpcra4tp9hl57jl0893a4r2r72jpsk39rjj'
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
nftProcess:
  parallelism: 1
  maxRetries: 3
